### ISSUE TITLE
ngx-jodit-pro:The cursor moves to the beginning of the content

### ISSUE THREAD

**Issue by Yang-Jing-Hui** [julianpoemp/ngx-jodit#15]
When I use some functions of the toolbar, such as: ul, ol, table, image, autocomplete..., the cursor will go to the beginning of the content.
Hopefully the cursor will stay where it is.

 In addition,

autocomplete: {
        insertValueRenderer: (item) => `<span style='color: rgb(78, 161, 242)' >@${item.value.Name}</span>`
      }
      
 when I use autocomplete, the cursor will move to the beginning of the content.
 Then I press End on the keyboard, the cursor does not go to the end of the line, but to the end of the span tag. As shown below:     
![image](https://github.com/julianpoemp/ngx-jodit/assets/139448915/fc52662d-acd3-49f4-9fd5-15b0cde4cdda)

I have to press the → on the keyboard for the cursor to be outside the span tag.

jodit-pro demo[https://xdsoft.net/jodit/pro/docs/plugin/autocomplete/](https://xdsoft.net/jodit/pro/docs/plugin/autocomplete/) does not have such a situation.

**Comment by julianpoemp** [comment]
@Yang-Jing-Hui please answer:

1. Version of ngx-jodit-pro?

2. Version of jodit-pro?

Please post the HTML snippet and the options (without license key). If you use plugins, please list the styles and scripts declarations, too.

That way it's easier to reproduce this :)

**Comment by julianpoemp** [comment]
@Yang-Jing-Hui I just released an update that may fix this issue. Please update to the next minor version. Depending if you use 1.x, 2.x or 3.x:

````
npm install --save ngx-jodit-pro@^1
````
or

````
npm install --save ngx-jodit-pro@2x
````
or

````
npm install --save ngx-jodit-pro@3x
````

**Comment by Yang-Jing-Hui** [comment]
I update ngx-jodit-pro version, the problem still exist.

I got it.
I guess it's because I put ngx-jodit-pro into the component to bind the content in two directions.
So when I update the content, it will be sent to the parent component, and then passed in from the parent component, so that the cursor is moved to the beginning of the content.
Haha I wonder if it is possible to support ngModel?

   "jodit": "^3.24.9",
    "jodit-pro": "^1.3.40",
    "ngx-jodit-pro": "^1.0.5",

**Comment by Yang-Jing-Hui** [comment]
Sorry for replying so late. Because when I use stackblitz, starting dev server keeps appearing for some reason, so that the code cannot be provided.

**Comment by Yang-Jing-Hui** [comment]
There seems to be some time difference with npm. I can't get the latest version now. I will try it tomorrow.
![image](https://github.com/julianpoemp/ngx-jodit/assets/139448915/d9bfd4d3-3299-4917-87a6-ae98e50d32af)

**Comment by Yang-Jing-Hui** [comment]
ngx-jodit-pro@1.0.6 fixes this issue. 
Awesome! Thank you! 
I'm a little confused, are (joditChange) and (valueChange) the same?

**Comment by julianpoemp** [comment]
@Yang-Jing-Hui joditChange triggers everytime when jodit.events.change triggers (even after something  changed via [value]). valueChange is part of [(value)] and emits in jodit.change only for changes that come from the editor but not from outside of ngx-jodit-pro. 
You can check out the code for better understanding. It's to prevent the "something has been changed after component checked" angular error.

**Comment by Yang-Jing-Hui** [comment]
I understand. Thank you ~

**Comment by julianpoemp** [comment]
Closing this. Thank you for reporting!
